version: '3.7'

networks:
  fabric-network:
    name: ${NETWORK_NAME}

services:
  ocr:
    build:
      context: ../ocr
      dockerfile: Dockerfile
    container_name: ocr-service
    environment:
      - IPFS_API_URL=http://ipfs:5001
      - OCR_LANGS=eng,ind
    ports:
      - "${OCR_API_PORT}:7070"
    networks:
      - fabric-network
    restart: unless-stopped
